### ISSUE TITLE
Add exception handling and logging

### ISSUE THREAD

**Issue by SubhrajitPrusty** [SubhrajitPrusty/codex-github#128]
- Add exception handling in case of wrong usernames and changed usernames, or database access failure.
Any unforseeable changes should not take down the website.
- Add logging

**Comment by punndcoder28** [comment]
Hey! Can I take this up?

**Comment by SubhrajitPrusty** [comment]
Sure

**Comment by punndcoder28** [comment]
Hey. Correct me if I am wrong. I need to add a try block in `userdata.py` to check for valid username and try block in `update.py` to check for database access. Is this right?

**Comment by SubhrajitPrusty** [comment]
yes

**Comment by punndcoder28** [comment]
Hey! I've open a PR #131. Could you take a look and get back to me if there are any issues?

**Comment by SubhrajitPrusty** [comment]
fixed by #131
