### ISSUE TITLE
Bug with "Members" bar in the website

### ISSUE THREAD

**Issue by LoopGlitch26** [SubhrajitPrusty/codex-github#145]
**Description**
This user finds it difficult to interpret the "Members" section on the website properly

**To Reproduce**
1. Go to http://codex-github.herokuapp.com/
2. On the home page itself, just above the "Members" section
4. See error as a white patch/bar on the dark mode

**Expected behavior**
This user finds it unusual. It might be a bug, bcz it doesn't seem to be a feature

**Screenshots**
![Screenshot (33)](https://user-images.githubusercontent.com/53336715/81471884-f1f9ca00-9211-11ea-8bb5-248d90f7029c.png)

**Desktop (please complete the following information):**
 - OS: WINDOWS 10 HSL
 - Browser: Chrome
 - Version: Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by SubhrajitPrusty** [comment]
@swagat5147 can you help with css of the background?

**Comment by swagat5147** [comment]
@SubhrajitPrusty will look into it after 15

**Comment by SubhrajitPrusty** [comment]
15 as in date or minutes?

**Comment by swagat5147** [comment]
15 as in date of this month

**Comment by SubhrajitPrusty** [comment]
OK
