### ISSUE TITLE
Commit are not getting added

### ISSUE THREAD

**Issue by geekyNehal** [SubhrajitPrusty/codex-github#58]
My commits are not getting added on the website.

**Comment by SubhrajitPrusty** [comment]
What do you think the actual number should be?

**Comment by geekyNehal** [comment]
The day before yesterday when I check the website I had 58 commits but after that, I did almost 10-12 commits but that remains the same on the website.

**Comment by SubhrajitPrusty** [comment]
Commits on different Organisations do not count.
Commits on someone else's repo (without forking) doesn't count

**Comment by SubhrajitPrusty** [comment]
Also private repos wont be counted obviously.
It says in your profile that you have made 4 commits in March.

**Comment by geekyNehal** [comment]
My repo is not private nor it is for any other organization it is a normal public repo in which I actually did commit to, else leave.

**Comment by SubhrajitPrusty** [comment]
Your profile says you've made only 4 commits to 3 repositories in March

**Comment by geekyNehal** [comment]
but that's not correct. You can check my [ExpenseTracker app](https://github.com/geekyNehal/ExpenseTrackerApp/commits/master) commits

**Comment by SubhrajitPrusty** [comment]
The commits that you are making to your repo are not verified. Github doesn't acknowledge them

**Comment by SubhrajitPrusty** [comment]
https://github.com/codex-iter/project-ideas/commits/master

What verified commits look like
