### ISSUE TITLE
Profile page for each users

### ISSUE THREAD

**Issue by SubhrajitPrusty** [SubhrajitPrusty/codex-github#68]
Each user should have a profile page generated from data received from github API (in the userdata file)

**Comment by punndcoder28** [comment]
Hey. Can I take this up? What do you mean when you say that you want a profile page generated? If you can guide me I will be more than happy to work on this.
Thanks.

**Comment by SubhrajitPrusty** [comment]
Hello. Thanks for your interest in this project.
Just FYI this was our institutes club project and the code may not be that polished.

And coming to the issue, by user pages, I mean - when you click on a user "card" it redirects to the user's github page.

I want to create a new template so that when you click on the user card, it redirects to a template where we can show details of the github user in our interface.

**Comment by SubhrajitPrusty** [comment]
done
