### ISSUE TITLE
Add a statistic that counts total contributions of club members

### ISSUE THREAD

**Issue by SubhrajitPrusty** [SubhrajitPrusty/codex-github#7]

**Comment by Adi2612** [comment]
@SubhrajitPrusty  
I think you need to add a proper documentation regarding proper steps required to run this application and what are all its dependencies.
then it will become easier for others to contribute.

**Comment by SubhrajitPrusty** [comment]
Yea I don't think it this is a good project for hacktoberfest. Sorry for the inconvenience.

**Comment by SubhrajitPrusty** [comment]
done
